name: Bitcoin Price Bot

on:
  schedule:
    - cron: "*/30 * * * *" # Roda a cada 30 minutos
  workflow_dispatch:  # Permite execução manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # O job será interrompido após 2 minutos
    steps:
      - name: Log de execução (para verificar se o cron está funcionando)
        run: echo "Workflow acionado automaticamente ou manualmente!"

      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Instalar dependências
        run: npm install

      - name: Rodar bot
        run: |
          echo "Iniciando o bot..."
          nohup node index.js &
          sleep 20 # Aguarda o serviço rodando por 5 segundos

      - name: Chamar o endpoint /preco e registrar resposta
        run: |
          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" http://localhost:3000/preco)
          echo "Código de resposta: $RESPONSE"
          echo "Corpo da resposta:"
          cat response.txt
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DEEPSEEK_TOKEN: ${{ secrets.DEEPSEEK_TOKEN }}
