name: Bitcoin Price Bot

on:
  schedule:
    - cron: "*/2 * * * *" # Executa a cada 30 minutos
  workflow_dispatch: # Permite execução manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 1  # Interrompe o job após 1 minuto
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Instalar dependências
        run: npm install

      - name: Verificar variáveis de ambiente
        run: echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" && echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}"

      - name: Rodar bot
        run: node index.js
        
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
