name: schedule preco

on:
  schedule:
    - cron: "*/30 * * * *" # Roda a cada 30 minutos
  workflow_dispatch:  # Permite execução manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # O job será interrompido após 2 minutos
    steps:
      - name: Log de execução (para verificar se o cron está funcionando)
        run: echo "Workflow acionado automaticamente ou manualmente!"

      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Instalar dependências
        run: npm install

      - name: Rodar bot
        run: |
          echo "Iniciando o bot..."
          TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} \
          TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} \
          DEEPSEEK_TOKEN=${{ secrets.DEEPSEEK_TOKEN }} \
          MONGO_USUARIO=${{ secrets.MONGO_USUARIO }} \
          MONGO_SENHA=${{ secrets.MONGO_SENHA }} \
          TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY }} \
          TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET }} \
          TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }} \
          TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} \
          nohup node index.js &
          sleep 5

      - name: Chamar o endpoint /preco e registrar resposta
        run: |
          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" http://localhost:3000/preco)
          echo "Código de resposta: $RESPONSE"
          echo "Corpo da resposta:"
          cat response.txt
